name: test Qt install on Mac

on: [push]

jobs:
  build:
    name: test Qt install
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install MacOS dependencies
        # MacOS already has libxml2 by default
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          brew install qt5 --with-developer